// Static content data (German, React, DSA, Aptitude) + glossary. Pure literals, no deps.
/* ═══════════════════════════ DATA ═══════════════════════════ */

export const DECKS = {
  selfintro: [
    { de: "Ich heiße Neel.", en: "My name is Neel.", note: "heißen = to be called" },
    { de: "Ich komme aus Indien.", en: "I come from India.", note: "kommen aus = come from" },
    { de: "Ich wohne in Mumbai.", en: "I live in Mumbai.", note: "wohnen in = live in" },
    { de: "Ich bin 19 Jahre alt.", en: "I am 19 years old.", note: "sein + Jahre alt" },
    { de: "Mein Hobby ist Kochen.", en: "My hobby is cooking." },
    { de: "Mein Geburtstag ist im Oktober.", en: "My birthday is in October.", note: "im + month" },
    { de: "Sie heißt Roshni.", en: "Her name is Roshni.", note: "3rd person: heißt" },
    { de: "Sie kommt aus Mumbai.", en: "She comes from Mumbai." },
    { de: "Sie wohnt in Mumbai.", en: "She lives in Mumbai." },
    { de: "Sie ist 19 Jahre alt.", en: "She is 19 years old." },
  ],
  greetings: [
    { de: "Hallo", en: "Hello (casual)", note: "informal, any time of day" },
    { de: "Guten Morgen", en: "Good morning" },
    { de: "Guten Tag", en: "Good day", note: "formal, daytime" },
    { de: "Guten Abend", en: "Good evening" },
    { de: "Gute Nacht", en: "Good night", note: "before sleeping" },
    { de: "Grüß Gott", en: "Hello (S. Germany / Austria)", note: "Bavaria / Austria" },
    { de: "Moin Moin", en: "Hi (N. Germany)", note: "northern Germany" },
  ],
  farewells: [
    { de: "Tschüss", en: "Bye", note: "informal" },
    { de: "Auf Wiedersehen", en: "Goodbye", note: "formal" },
    { de: "Servus", en: "Hi / Bye", note: "southern Germany & Austria" },
    { de: "Bis bald", en: "See you soon" },
    { de: "Bis später", en: "See you later", note: "same day" },
  ],
  mood: [
    { de: "Wie geht es Ihnen?", en: "How are you? (formal)" },
    { de: "Wie geht's?", en: "How's it going? (casual)" },
    { de: "Mir geht es gut.", en: "I'm doing well." },
    { de: "Mir geht es sehr gut.", en: "I'm doing very well." },
    { de: "Es geht.", en: "I'm okay / so-so." },
    { de: "Mir geht es schlecht.", en: "I'm not feeling well." },
    { de: "Ich bin müde.", en: "I'm tired." },
    { de: "Ich bin krank.", en: "I'm sick." },
    { de: "Und dir?", en: "And you? (informal)" },
    { de: "Auch gut, danke.", en: "Also good, thanks." },
  ],
  questions: [
    { de: "Wie heißt du?", en: "What's your name?", note: "formal: Wie heißen Sie?" },
    { de: "Woher kommst du?", en: "Where are you from?", note: "formal: Woher kommen Sie?" },
    { de: "Wo wohnst du?", en: "Where do you live?", note: "formal: Wo wohnen Sie?" },
    { de: "Wie alt bist du?", en: "How old are you?" },
    { de: "Was ist dein Hobby?", en: "What is your hobby?" },
    { de: "Wann hast du Geburtstag?", en: "When is your birthday?" },
    { de: "Wie ist deine Handynummer?", en: "What's your phone number?" },
  ],
  days: [
    { de: "Montag", en: "Monday" }, { de: "Dienstag", en: "Tuesday" },
    { de: "Mittwoch", en: "Wednesday" }, { de: "Donnerstag", en: "Thursday" },
    { de: "Freitag", en: "Friday" }, { de: "Samstag", en: "Saturday" },
    { de: "Sonntag", en: "Sunday" }, { de: "das Wochenende", en: "the weekend", note: "Sa + So" },
  ],
  months: [
    { de: "Januar", en: "January" }, { de: "Februar", en: "February" },
    { de: "März", en: "March" }, { de: "April", en: "April" },
    { de: "Mai", en: "May" }, { de: "Juni", en: "June" },
    { de: "Juli", en: "July" }, { de: "August", en: "August" },
    { de: "September", en: "September" }, { de: "Oktober", en: "October" },
    { de: "November", en: "November" }, { de: "Dezember", en: "December" },
  ],
  family: [
    { de: "der Vater", en: "father" }, { de: "die Mutter", en: "mother" },
    { de: "der Sohn", en: "son" }, { de: "die Tochter", en: "daughter" },
    { de: "der Bruder", en: "brother" }, { de: "die Schwester", en: "sister" },
    { de: "der Großvater", en: "grandfather" }, { de: "die Großmutter", en: "grandmother" },
    { de: "der Ehemann", en: "husband" }, { de: "die Ehefrau", en: "wife" },
    { de: "der Onkel", en: "uncle" }, { de: "die Tante", en: "aunt" },
  ],
  hobbies: [
    { de: "Kochen", en: "cooking" }, { de: "Schwimmen", en: "swimming" },
    { de: "Lesen", en: "reading" }, { de: "Reisen", en: "traveling" },
    { de: "Tanzen", en: "dancing" }, { de: "Musik hören", en: "listening to music" },
    { de: "Fußball spielen", en: "playing football" }, { de: "Singen", en: "singing" },
    { de: "Malen", en: "painting" }, { de: "Laufen", en: "running" },
    { de: "Schreiben", en: "writing" }, { de: "Computerspiele spielen", en: "playing video games" },
  ],
  countries: [
    { de: "Deutschland", lang: "Deutsch", note: "Germany" },
    { de: "Österreich", lang: "Deutsch", note: "Austria" },
    { de: "die Schweiz", lang: "Deutsch, Französisch, Italienisch", note: "Switzerland" },
    { de: "Frankreich", lang: "Französisch", note: "France" },
    { de: "Großbritannien", lang: "Englisch", note: "Great Britain" },
    { de: "Italien", lang: "Italienisch", note: "Italy" },
    { de: "Spanien", lang: "Spanisch", note: "Spain" },
    { de: "Japan", lang: "Japanisch", note: "Japan" },
    { de: "China", lang: "Chinesisch", note: "China" },
    { de: "Polen", lang: "Polnisch", note: "Poland" },
    { de: "Schweden", lang: "Schwedisch", note: "Sweden" },
    { de: "Griechenland", lang: "Griechisch", note: "Greece" },
    { de: "Mexiko", lang: "Spanisch", note: "Mexico" },
  ],
  time: [
    { de: "Viertel nach sechs", en: "quarter past six (6:15)", note: "nach = past" },
    { de: "Viertel vor zehn", en: "quarter to ten (9:45)", note: "vor = to/before" },
    { de: "halb eins", en: "12:30", note: "halb = halfway to NEXT hour" },
    { de: "halb neun", en: "8:30", note: "halfway to 9" },
    { de: "zehn nach drei", en: "3:10", note: "ten past three" },
    { de: "zehn vor sieben", en: "6:50", note: "ten to seven" },
    { de: "Wie spät ist es?", en: "What time is it?" },
    { de: "Wieviel Uhr ist es?", en: "What time is it? (alt.)" },
  ],
  phrases: [
    { de: "Ich verstehe nicht.", en: "I don't understand." },
    { de: "Können Sie das bitte wiederholen?", en: "Can you repeat that, please?" },
    { de: "Wie heißt das auf Deutsch?", en: "What's that in German?" },
    { de: "Was ist das?", en: "What is that?" },
    { de: "Entschuldigung", en: "Sorry / Excuse me" },
    { de: "Vielen Dank!", en: "Thank you very much!" },
    { de: "Darf ich reinkommen?", en: "May I come in?" },
    { de: "Ich weiß es nicht.", en: "I don't know." },
  ],
};

export const VERBS = [
  { inf: "heißen", m: "to be called", f: { ich: "heiße", du: "heißt", "er/sie/es": "heißt", "sie/Sie": "heißen" } },
  { inf: "wohnen", m: "to live",      f: { ich: "wohne", du: "wohnst", "er/sie/es": "wohnt", "sie/Sie": "wohnen" } },
  { inf: "kommen", m: "to come",      f: { ich: "komme", du: "kommst", "er/sie/es": "kommt", "sie/Sie": "kommen" } },
  { inf: "haben",  m: "to have",      f: { ich: "habe",  du: "hast",   "er/sie/es": "hat",   "sie/Sie": "haben" } },
  { inf: "sein",   m: "to be (irr.)", f: { ich: "bin",   du: "bist",   "er/sie/es": "ist",   "sie/Sie": "sind" } },
];

// True/False — each has German statement, correct bool, explanation, and English translation
export const TF = [
  { t: "Mittwoch bedeutet Wednesday.",                      a: true,  e: "Mittwoch = Wednesday ✓",                  en: "Wednesday means Wednesday." },
  { t: "Donnerstag bedeutet Tuesday.",                      a: false, e: "Donnerstag = Thursday (Dienstag = Tue.)", en: "Thursday means Tuesday. (False — it's Thursday.)" },
  { t: "Die Zahl 7 heißt 'sieben'.",                       a: true,  e: "7 = sieben ✓",                            en: "The number 7 is called 'sieben'." },
  { t: "Die Zahl 9 heißt 'sieben'.",                       a: false, e: "9 = neun, nicht sieben.",                 en: "The number 9 is called 'sieben'. (False — 9 = neun.)" },
  { t: "In Frankreich spricht man Französisch.",            a: true,  e: "France → French ✓",                      en: "In France, people speak French." },
  { t: "In Österreich spricht man Spanisch.",               a: false, e: "Österreich spricht Deutsch.",             en: "In Austria, people speak Spanish. (False — Deutsch.)" },
  { t: "Italien ist ein Nachbarland von Deutschland.",      a: false, e: "Italy does NOT border Germany.",          en: "Italy is a neighbor of Germany. (False!)" },
  { t: "Polen ist ein Nachbarland von Deutschland.",        a: true,  e: "Poland borders Germany ✓",               en: "Poland is a neighboring country of Germany." },
  { t: "'halb eins' bedeutet 12:30 Uhr.",                  a: true,  e: "halb eins = halfway to 1 = 12:30 ✓",     en: "'half one' means 12:30." },
  { t: "'Viertel vor zehn' bedeutet 10:15 Uhr.",           a: false, e: "Viertel vor zehn = 9:45, nicht 10:15.",  en: "'Quarter before ten' means 10:15. (False — it's 9:45.)" },
  { t: "'du kommst' ist die richtige Form von 'kommen'.",  a: true,  e: "du + -st stem ✓",                        en: "'du kommst' is the correct form of 'kommen' (to come)." },
  { t: "'ich bin' ist die richtige Form von 'sein'.",      a: true,  e: "sein is irregular: ich bin ✓",           en: "'ich bin' is the correct form of 'sein' (to be)." },
  { t: "'er habt' ist die richtige Form von 'haben'.",     a: false, e: "Correct: er hat (nicht habt).",          en: "'er habt' is the correct form of 'haben'. (False — 'er hat'.)" },
  { t: "'Guten Morgen' sagt man am Morgen.",               a: true,  e: "Used in the morning ✓",                  en: "One says 'Good morning' in the morning." },
  { t: "'Gute Nacht' sagt man zur Begrüßung am Morgen.",  a: false, e: "Gute Nacht = bedtime, not morning.",     en: "'Good night' is said as a morning greeting. (False — bedtime.)" },
  { t: "'Tschüss' ist informell.",                         a: true,  e: "Tschüss = casual bye ✓",                 en: "'Tschüss' is informal." },
  { t: "'Auf Wiedersehen' ist informell.",                  a: false, e: "Auf Wiedersehen = formal.",              en: "'Auf Wiedersehen' is informal. (False — it's formal.)" },
  { t: "Das Wochenende ist Samstag und Sonntag.",          a: true,  e: "Wochenende = Sa + So ✓",                 en: "The weekend is Saturday and Sunday." },
  { t: "Es gibt 12 Monate im Jahr.",                       a: true,  e: "12 months ✓",                            en: "There are 12 months in the year." },
  { t: "Dezember ist der erste Monat des Jahres.",         a: false, e: "Januar is first.",                       en: "December is the first month of the year. (False — January is.)" },
  { t: "'Vater' bedeutet 'father'.",                       a: true,  e: "Vater = father ✓",                       en: "'Vater' means 'father'." },
  { t: "'Schwester' bedeutet 'brother'.",                  a: false, e: "Schwester = sister (Bruder = brother).", en: "'Schwester' means 'brother'. (False — it means 'sister'.)" },
  { t: "Die Schweiz ist ein Nachbarland von Deutschland.", a: true,  e: "Switzerland borders Germany ✓",          en: "Switzerland is a neighboring country of Germany." },
  { t: "'fünfundzwanzig' bedeutet 52.",                   a: false, e: "fünfundzwanzig = 25.",                   en: "'fünfundzwanzig' means 52. (False — it means 25.)" },
];

export const PASSAGES = [
  {
    text: "Das ist Rose Lewis. Sie kommt aus den USA und wohnt in San Francisco. Sie spricht Englisch und Deutsch. Sie lernt Spanisch.",
    en: "This is Rose Lewis. She comes from the USA and lives in San Francisco. She speaks English and German. She is learning Spanish.",
    q: [
      { q: "Woher kommt Rose?", qen: "Where does Rose come from?", a: "den USA", o: ["den USA", "Österreich", "China", "Algerien"] },
      { q: "Wo wohnt Rose?", qen: "Where does Rose live?", a: "San Francisco", o: ["San Francisco", "Salzburg", "Genf", "Shanghai"] },
      { q: "Welche Sprache lernt Rose?", qen: "What language is Rose learning?", a: "Spanisch", o: ["Spanisch", "Arabisch", "Deutsch", "Französisch"] },
    ],
  },
  {
    text: "Das ist Boris Walder. Er kommt aus Österreich und wohnt in Salzburg. Er spricht Deutsch und Englisch. Er lernt Arabisch.",
    en: "This is Boris Walder. He comes from Austria and lives in Salzburg. He speaks German and English. He is learning Arabic.",
    q: [
      { q: "Woher kommt Boris?", qen: "Where does Boris come from?", a: "Österreich", o: ["Österreich", "den USA", "Algerien", "China"] },
      { q: "Wo wohnt Boris?", qen: "Where does Boris live?", a: "Salzburg", o: ["Salzburg", "San Francisco", "Genf", "Shanghai"] },
      { q: "Was lernt Boris?", qen: "What is Boris learning?", a: "Arabisch", o: ["Arabisch", "Spanisch", "Deutsch", "Chinesisch"] },
    ],
  },
  {
    text: "Das ist Kateb Brahim. Er kommt aus Algerien und wohnt in Genf. Er spricht Arabisch und Französisch. Er lernt Deutsch.",
    en: "This is Kateb Brahim. He comes from Algeria and lives in Geneva. He speaks Arabic and French. He is learning German.",
    q: [
      { q: "Woher kommt Kateb?", qen: "Where does Kateb come from?", a: "Algerien", o: ["Algerien", "Österreich", "den USA", "China"] },
      { q: "Wo wohnt Kateb?", qen: "Where does Kateb live?", a: "Genf", o: ["Genf", "Salzburg", "Shanghai", "San Francisco"] },
      { q: "Welche Sprachen spricht Kateb?", qen: "What languages does Kateb speak?", a: "Arabisch und Französisch", o: ["Arabisch und Französisch", "Englisch und Deutsch", "Chinesisch und Deutsch", "Spanisch"] },
    ],
  },
];

export const EN2DE = [
  { en: "My name is Neel.", de: "Ich heiße Neel." },
  { en: "I come from India.", de: "Ich komme aus Indien." },
  { en: "I live in Mumbai.", de: "Ich wohne in Mumbai." },
  { en: "I am 19 years old.", de: "Ich bin 19 Jahre alt." },
  { en: "My hobby is cooking.", de: "Mein Hobby ist Kochen." },
  { en: "Good morning", de: "Guten Morgen" },
  { en: "Good evening", de: "Guten Abend" },
  { en: "Good night", de: "Gute Nacht" },
  { en: "Goodbye (formal)", de: "Auf Wiedersehen" },
  { en: "Bye (informal)", de: "Tschüss" },
  { en: "See you soon", de: "Bis bald" },
  { en: "How are you? (formal)", de: "Wie geht es Ihnen?" },
  { en: "I'm doing well.", de: "Mir geht es gut." },
  { en: "And you? (informal)", de: "Und dir?" },
  { en: "I'm tired.", de: "Ich bin müde." },
  { en: "I don't understand.", de: "Ich verstehe nicht." },
  { en: "Thank you very much!", de: "Vielen Dank!" },
  { en: "Excuse me / Sorry", de: "Entschuldigung" },
  { en: "What's your name? (informal)", de: "Wie heißt du?" },
  { en: "Where are you from? (informal)", de: "Woher kommst du?" },
  { en: "How old are you?", de: "Wie alt bist du?" },
  { en: "Where do you live? (informal)", de: "Wo wohnst du?" },
  { en: "What is your hobby?", de: "Was ist dein Hobby?" },
  { en: "Can you repeat that, please?", de: "Können Sie das bitte wiederholen?" },
];

/* ─── REACT subject: MCQ question bank ─── */
export const REACT_QUIZ = [
  { q: "What type of components can use React Hooks?", o: ["Class components only", "Plain HTML files linked to JavaScript assets", "Functional components only", "Only layout components inside the public directory"], c: "C" },
  { q: "Why might a React Single Page Application (SPA) show a 404 error when refreshing a sub-route on Netlify?", o: ["The application code is too large for the hosting environment", "The production build automatically deletes sub-route components", "The server tries to look for a physical file matching that path instead of routing to index.html", "Vite doesn't support nested routing links during compilation step"], c: "C" },
  { q: "If you want a child component to send data back up to a parent, what do you pass as a prop?", o: ["The child component's local state hook object", "A modified string parameter", "A callback function defined in the parent component", "A standard link tag pointing upwards"], c: "C" },
  { q: "What does the useState Hook return?", o: ["A single object matching all HTML data properties", "The state value string directly without any extra tools", "A promise that resolves when the page updates", "An array containing the current state value and a setter function"], c: "D" },
  { q: "When deploying a Vite React app, what is the default command to build production-ready optimized static files?", o: ["vite start-app", "npm run build", "npm execute production", "npm run dev"], c: "B" },
  { q: "What feature allows Netlify or Vercel to automatically rebuild your site whenever you push changes to GitHub?", o: ["Continuous Deployment (CD) integration hooks", "Node package manager installation triggers", "Local file watcher background cron scripts", "Browser extension tracking modules"], c: "A" },
  { q: "What does an empty dependency array [] mean inside a useEffect Hook?", o: ["The effect will run on every single re-render block", "The effect will only run once when the component mounts", "The effect is turned off and will never execute at all", "The effect only triggers when state arrays are completely cleared"], c: "B" },
  { q: "Why shouldn't you do 'state = NewValue' directly to update a state variable?", o: ["It will cause an immediate compiler crash in Vite", "It converts the variable into a fixed prop value", "React won't detect the change, and the UI won't update", "It deletes all other variables inside your component folder"], c: "C" },
  { q: "What is the direction of data flow when using props?", o: ["Global (randomly between any component files)", "Bidirectional (back and forth evenly)", "Upwards only (from child to parent component)", "Unidirectional (downwards from parent to child)"], c: "D" },
  { q: "Which of these is an example of imperative programming?", o: ["Using a conditional ternary operator in JSX", "Mapping an array to a list of elements", "Using document.getElementById('title').textContent = 'Hello'", "Returning <h1>Hello</h1> from a React component"], c: "C" },
  { q: "What can a React component return?", o: ["Only standard HTML <div> tags", "Any valid CSS styling sheets", "JSON data objects only", "JSX elements, strings, numbers, or null"], c: "D" },
  { q: "Do React Fragments appear inside the final browser HTML DOM tree?", o: ["Only when the application is running in production mode", "Yes, they render as a <fragment> tag", "Yes, they automatically turn into a <div> tag", "No, they disappear and leave only their child elements"], c: "D" },
  { q: "What does 'declarative programming' mean in React?", o: ["You describe what the UI should look like, and React handles the updates", "You write step-by-step instructions to change the DOM manually", "You have to reload the entire webpage to change data", "You cannot use any JavaScript functions"], c: "A" },
  { q: "What technology does React use to declaratively render UI components?", o: ["Sass scripts", "SQL", "JSX", "Python templates"], c: "C" },
  { q: "Which built-in React Hook is used to track and update local component state?", o: ["useContext", "useRef", "useState", "useEffect"], c: "C" },
  { q: "How do you install components from shadcn/ui into a local project structure?", o: ["Manually writing all accessible element parameters from scratch", "Downloading an immutable npm package that you cannot modify", "Using their specialized CLI command tool to add specific files", "Linking a global CDN script tag into the index.html template"], c: "C" },
  { q: "In React, component names must always start with which type of letter?", o: ["A number symbol", "A lowercase letter", "An underscore character", "A capital letter"], c: "D" },
  { q: "What tool is commonly used to create an optimized, modern React app build environment instead of Create React App?", o: ["Vite", "Babel Core scripts", "Nodemon instance", "Webpack CLI 1"], c: "A" },
  { q: "What can be passed as a prop to a React component?", o: ["Strings, numbers, arrays, objects, and even functions", "Only plain text strings", "Only valid CSS stylesheets", "Only hook state variables"], c: "A" },
  { q: "What happens to a component when its state updates?", o: ["The component crashes and displays an error box", "The entire webpage undergoes a full hard refresh", "The component automatically re-renders to reflect the new state", "The browser clears its local storage cache memory"], c: "C" },
  { q: "How are props passed into a React component?", o: ["As global browser cookies", "Via a database connection string", "Through an import statement at the top of the file", "Like custom attributes on HTML tags"], c: "D" },
  { q: "Can you create your own custom Hooks in React?", o: ["Yes, by writing a function whose name starts with the prefix 'use'", "Only when building a mobile layout using special extensions", "Yes, but they must be registered inside the package.json file", "No, only the built-in React team hooks can ever be run"], c: "A" },
  { q: "What folder does Vite output its production-ready static assets into by default?", o: ["public", "build", "out", "dist"], c: "D" },
  { q: "Which of these best describes component 'state'?", o: ["Like global variables tracked by an analytics server", "Like local variables declared inside a function block", "Like function arguments sent from a different file", "Like HTML tag properties defined in index.html"], c: "B" },
  { q: "If both props and state change at the same time, what does React do?", o: ["It stops rendering entirely until a manual restart happens", "It ignores the props and only updates the state layout", "Schedulers trigger a re-render of the component to display current data", "It throws an overlapping data collision alert box"], c: "C" },
  { q: "What configuration file or rule fixes sub-routing 404 issues for a React app hosted on Netlify?", o: ["Re-installing the vite dependency tool chain using npm", "A _redirects rule file or netlify.toml setup mapping to index.html", "Adding a homepage attribute to the project package.json configuration", "A clean script entry inside the tailwind config utility"], c: "B" },
  { q: "Which tool does shadcn/ui rely on under the hood to handle component styling utilities cleanly?", o: ["Vanilla inline-styles objects", "Bootstrap Framework", "Sass preprocessor modules", "Tailwind CSS"], c: "D" },
  { q: "What file is typically edited to configure path tracking aliases and utilities for Tailwind CSS?", o: ["postcss.config.js", "index.html", "tailwind.config.js", "vite.config.js"], c: "C" },
  { q: "Which of these variables should be handled with 'state' rather than 'props'?", o: ["The styling color scheme passed from a layout root", "A fixed background image URL string", "Whether a user dropdown menu is currently open or closed", "A static application brand name text"], c: "C" },
  { q: "In vanilla JS, adding a class using element.classList.add() is an example of what?", o: ["Imperative programming", "Asynchronous routing", "State management", "Declarative programming"], c: "A" },
];
export const LETTER_IDX = { A: 0, B: 1, C: 2, D: 3 };

/* ─── REACT module flashcards (front=question, back=answer), from the course syllabus ─── */
export const REACT_MODULE_CARDS = [
  // Intro & setup, modern JS
  ["Intro", "What problem does React solve?", "Building interactive UIs by describing what the UI should look like for a given state; React efficiently updates the DOM when state changes."],
  ["Intro", "What is Create React App (CRA)?", "An older official toolchain to scaffold a React project with zero build config. Modern projects prefer Vite."],
  ["Intro", "What does the React virtual DOM do?", "Keeps an in-memory tree of the UI; on state change React diffs (reconciles) it against the previous tree and applies only the minimal real-DOM updates."],
  ["Modern JS", "What does ES6 destructuring let you do in React?", "Pull values out of props/state/arrays concisely, e.g. const { title } = props or const [v, setV] = useState()."],
  ["Modern JS", "Why are arrow functions common in React?", "They have no own 'this' binding, so callbacks and inline handlers behave predictably inside components."],
  ["Modern JS", "What is the spread operator used for in React?", "Copying/merging arrays and objects immutably, e.g. setState updates like {...obj, key: val} or [...arr, item]."],
  // Components & props
  ["Components", "What is a functional component?", "A JavaScript function that takes props and returns JSX. The modern standard for React components."],
  ["Components", "What are props?", "Read-only inputs passed from a parent to a child component, like attributes on a tag. A child must not mutate them."],
  ["Components", "What is PropTypes used for?", "Runtime validation of a component's prop types (e.g. PropTypes.string.isRequired) to catch bugs during development."],
  ["Components", "How do you pass data from child to parent?", "The parent passes a callback function as a prop; the child calls it with the data."],
  // JSX
  ["JSX", "What is JSX?", "A syntax extension that lets you write HTML-like markup in JavaScript; it compiles to React.createElement calls."],
  ["JSX", "How do you write a conditional in JSX?", "Use a ternary {cond ? <A/> : <B/>} or short-circuit {cond && <A/>}; if/else statements can't go inside JSX directly."],
  ["JSX", "Why does each item in a mapped list need a key?", "Keys give React stable identity for list items so it can update them efficiently and correctly across re-renders."],
  ["JSX", "Why use className instead of class in JSX?", "'class' is a reserved word in JavaScript, so JSX uses className for the HTML class attribute."],
  // Hooks
  ["Hooks", "What does useState return?", "An array: [currentValue, setterFunction]. Calling the setter schedules a re-render with the new value."],
  ["Hooks", "What does useEffect do?", "Runs side effects (data fetching, subscriptions, DOM work) after render, controlled by its dependency array."],
  ["Hooks", "What does an empty useEffect dependency array [] mean?", "The effect runs once after the component mounts (and its cleanup runs on unmount)."],
  ["Hooks", "What is a useEffect cleanup function?", "The function you return from the effect; React runs it before the next effect run and on unmount (e.g. to remove listeners)."],
  ["Hooks", "What is useContext for?", "Reading a value from a React Context without prop-drilling, giving components access to shared/global state."],
  ["Hooks", "When should you use useReducer instead of useState?", "When state logic is complex or the next state depends on the previous one, or multiple sub-values change together."],
  ["Hooks", "What is a custom hook?", "A reusable function whose name starts with 'use' that calls other hooks to share stateful logic between components."],
  ["Hooks", "What is useRef commonly used for?", "Holding a mutable value that persists across renders without causing re-renders, and referencing DOM nodes."],
  ["Hooks", "What does useMemo do?", "Memoizes the result of an expensive calculation, recomputing only when its dependencies change."],
  ["Hooks", "What is the Rules of Hooks?", "Only call hooks at the top level of a component or custom hook, never inside loops/conditions, and only from React functions."],
  // State management / Redux
  ["State Mgmt", "What is the Context API?", "React's built-in way to share state app-wide via a Provider that supplies a value to all consuming components."],
  ["State Mgmt", "What is Redux Toolkit (RTK)?", "The official, opinionated way to write Redux with less boilerplate — configureStore, createSlice, and built-in Immer."],
  ["State Mgmt", "What is a Redux slice?", "A piece of the store created with createSlice, bundling its reducer logic and auto-generated action creators."],
  ["State Mgmt", "What is Redux Thunk?", "Middleware that lets action creators return functions, enabling async logic like API calls before dispatching."],
  ["State Mgmt", "Context API vs Redux — when to use which?", "Context for low-frequency global values (theme, auth); Redux/RTK for large, frequently-updated, complex app state."],
  // Routing
  ["Routing", "What does React Router do?", "Maps URL paths to components for client-side routing in a single-page app, without full page reloads."],
  ["Routing", "How do you read a route parameter in React Router v6?", "Define a path like /user/:id and read it with the useParams() hook."],
  ["Routing", "How do you make a protected route?", "Wrap or guard the route so it renders the page only if authenticated, otherwise redirect (e.g. <Navigate to='/login' />)."],
  ["Routing", "Why does a refreshed SPA sub-route 404 on static hosts?", "The server looks for a real file at that path; you must add a rewrite/redirect rule sending all paths to index.html."],
  // Forms
  ["Forms", "What is a controlled component?", "A form input whose value is driven by React state and updated via onChange, making React the single source of truth."],
  ["Forms", "What is Formik used for?", "Managing form state, validation, and submission in complex React forms with less manual wiring."],
  // Styling
  ["Styling", "What do CSS Modules provide?", "Locally-scoped CSS class names per component, avoiding global style collisions."],
  ["Styling", "What are Styled Components?", "A CSS-in-JS library to define styled React components with tagged template literals and dynamic, prop-based styles."],
  // Performance
  ["Performance", "What does React.memo do?", "Memoizes a component so it skips re-rendering when its props are unchanged (shallow comparison)."],
  ["Performance", "What is lazy loading with React.lazy and Suspense?", "Code-splitting that loads a component only when needed, showing a Suspense fallback while it loads — smaller initial bundle."],
  ["Performance", "What is useCallback for?", "Memoizing a function identity across renders so memoized children/effects don't re-run unnecessarily."],
  // Testing
  ["Testing", "What is Jest?", "A JavaScript testing framework used to run unit/integration tests and make assertions in React projects."],
  ["Testing", "What is React Testing Library (RTL)?", "A library for testing components the way users interact with them — querying by role/text rather than implementation details."],
  ["Testing", "Why mock API calls in tests?", "To test components in isolation deterministically, without real network requests or flaky external dependencies."],
  // API
  ["API", "How do you fetch data with the Fetch API in React?", "Call fetch() inside useEffect, await res.json(), and store the result in state (handle loading and errors)."],
  ["API", "Why use Axios over Fetch?", "Axios adds conveniences: automatic JSON parsing, request/response interceptors, timeouts, and simpler error handling."],
  // Persistence
  ["Persistence", "How do you persist state in localStorage?", "Write state to localStorage.setItem on change (e.g. in an effect) and read it back with getItem on initialization."],
  ["Persistence", "What is Redux Persist?", "A library that saves and rehydrates the Redux store to storage so state survives page reloads/sessions."],
  // Animation
  ["Animation", "What is React Transition Group?", "A small library that manages mount/unmount transition states so you can animate components entering and leaving."],
  ["Animation", "What is Framer Motion?", "A declarative animation library (the 'motion' package) for animations, gestures, and layout transitions in React."],
  // TypeScript
  ["TypeScript", "Why use TypeScript with React?", "Static typing catches errors at compile time and gives autocomplete/safety for props, state, and hooks."],
  ["TypeScript", "How do you type a component's props in TS?", "Define an interface/type for the props and annotate the component, e.g. function Btn({label}: {label: string})."],
  // Next.js
  ["Next.js", "What is Next.js?", "A React framework adding server-side rendering, static generation, file-based routing, and full-stack features."],
  ["Next.js", "What is file-based routing in Next.js?", "Routes are created automatically from files in the app/pages directory — the file path becomes the URL."],
  // Deployment
  ["Deployment", "What does 'npm run build' produce?", "An optimized, minified production bundle of static assets ready to deploy (Vite outputs it to the dist folder)."],
  ["Deployment", "What is Continuous Deployment on Netlify/Vercel?", "Connecting your Git repo so every push triggers an automatic rebuild and redeploy of the site."],
];

/* ─── React flashcards from the professor's notes (links provided in class) ─── */
export const REACT_PROF_CARDS = [
  // Imperative vs Declarative
  ["Imperative vs Declarative", "What does imperative coding focus on?", "The step-by-step HOW — you explicitly tell the machine each step (e.g. createElement, textContent, appendChild)."],
  ["Imperative vs Declarative", "What does declarative coding focus on?", "The WHAT / the result you want; the framework handles the implementation. React is declarative — you describe the UI and React updates the DOM."],
  ["Imperative vs Declarative", "Prof's food analogy for the two paradigms?", "Imperative = a recipe's steps ('heat pan, add oil, wait 30s'); declarative = ordering the result ('grilled chicken, medium, with fries')."],
  // useState
  ["Prof · useState", "Why can't a plain JS variable hold React state?", "Plain variables don't trigger a re-render. Only updating state via its setter makes React re-render and show the change."],
  ["Prof · useState", "Why doesn't a const state variable cause an assignment error?", "The setter never mutates the variable — it schedules a future update. React re-runs the component with a fresh value in a new scope."],
  ["Prof · useState", "What is the state value during one render?", "A read-only, frozen snapshot for that render. The setter dispatches a new value for the next render."],
  ["Prof · useState", "How are useState's value and setter named?", "By array destructuring on index position ([value, setter]), so you can name them anything; multiple useState calls stay independent."],
  // useEffect
  ["Prof · useEffect", "What is useEffect's primary purpose?", "To safely run side effects (API calls, timers, DOM work) after the component renders and the DOM updates."],
  ["Prof · useEffect", "What does no dependency array (undefined) do?", "The effect runs after every render — which can cause performance issues or infinite loops."],
  ["Prof · useEffect", "What does a populated dependency array do?", "The effect runs on mount and re-runs only when one of the listed dependencies changes value."],
  ["Prof · useEffect", "What is the returned cleanup function for?", "React runs it before the next effect and on unmount — to remove listeners, cancel timers, and prevent memory leaks."],
  // useRef
  ["Prof · useRef", "What are useRef's two main roles?", "Direct DOM access for imperative tasks, and storing mutable data that persists across renders without triggering a re-render."],
  ["Prof · useRef", "How does useRef differ from useState on re-rendering?", "Changing a ref's .current does NOT cause a re-render; changing state always does."],
  ["Prof · useRef", "What does ref.current hold?", "Either the initial value you passed, or the actual DOM node once the ref is bound to a JSX element."],
  ["Prof · useRef", "Good use cases for useRef?", "Focus control, smooth scrolling, storing timer IDs, integrating DOM libraries, and caching previous values for comparison."],
  // useCallback
  ["Prof · useCallback", "Why are functions recreated each render, and why does it matter?", "Every re-render redefines inner functions; a child sees a 'new' function prop each time, causing unnecessary re-renders."],
  ["Prof · useCallback", "What does useCallback do?", "Memoizes a function so its reference stays stable across renders unless its dependencies change."],
  ["Prof · useCallback", "What must you pair useCallback with to actually prevent child re-renders?", "React.memo on the child — so it skips rendering when props (including the memoized function) are unchanged."],
  // useReducer
  ["Prof · useReducer", "What is useReducer and when is it used?", "The 'Manager' hook for complex state — when the next state depends on the previous, or multiple related values change together."],
  ["Prof · useReducer", "How does useReducer organize update logic?", "All update logic lives in one pure reducer(state, action) function; the component just dispatches actions ({type, payload})."],
  ["Prof · useReducer", "What does useReducer return?", "[state, dispatch] = useReducer(reducer, initialState)."],
  ["Prof · useReducer", "Prof's kitchen analogy?", "useState is a waiter who also cooks (fine for a small menu); useReducer is a professional kitchen — logic is separated from the UI."],
  // State vs Props
  ["Prof · State vs Props", "What is state (personal memory)?", "A component's local, changeable data; when it updates, React automatically re-renders to show the new data."],
  ["Prof · State vs Props", "How do props differ from state?", "Props are configuration passed parent→child and are read-only; state is managed locally inside a component and is changeable."],
  ["Prof · State vs Props", "Common parent/child pattern?", "The parent holds the state and passes it down to the child as a prop; only the parent can update its own state."],
  // ESLint
  ["Prof · ESLint", "What is ESLint?", "A code-quality checker — a 'grammar checker for code' that scans JS for errors, bad practices, and inconsistencies, running on build."],
  ["Prof · ESLint", "ESLint's four error categories?", "Syntax errors, bad practices (unused variables), style issues (naming/spacing), and potential bugs (e.g. == instead of ===)."],
  ["Prof · ESLint", "Why does React warn about mixed exports (only-export-components)?", "Don't export a component and non-components from the same file (breaks Fast Refresh); split constants/helpers into separate files."],
  ["Prof · ESLint", "How to avoid a setState-in-useEffect cascade when reading localStorage?", "Don't setState in an empty-deps effect (infinite loop); use lazy initialization: useState(() => JSON.parse(localStorage.getItem(k)) || [])."],
  // Fragments (link was dead; standard fact)
  ["Components", "What is a React Fragment and why use it?", "<>...</> (or <React.Fragment>) groups multiple children without adding an extra DOM node — return several elements without a wrapper div."],
];

/* ═══════════════════════════ DSA SUBJECT ═══════════════════════════ */
// Professor's MCQ bank (deduplicated). { q, o:[4 options], c: correct letter }
export const DSA_QUIZ = [
  { q: "What type of algorithmic strategy does Merge Sort use?", o: ["Divide and Conquer", "Dynamic Programming", "Brute Force", "Greedy Approach"], c: "A" },
  { q: "What is the worst-case time complexity of Bubble Sort?", o: ["O(n)", "O(n^2)", "O(1)", "O(n log n)"], c: "B" },
  { q: "Which sorting algorithm is generally stable and guarantees O(n log n) time complexity in all cases?", o: ["Quick Sort", "Bubble Sort", "Selection Sort", "Merge Sort"], c: "D" },
  { q: "If an In-order traversal of a BST reads [3, 5, 7, 10, 12], what is definitely true about node 3?", o: ["It is at the bottom-right of the layout", "It is the smallest element in the BST", "It is the root of the tree", "It has the most child references"], c: "B" },
  { q: "What happens during a single complete pass of Bubble Sort over an unsorted array?", o: ["The array is split into two equal halves", "The largest remaining element 'bubbles up' to its correct final position at the end", "The smallest element is placed at index 0", "Elements are sorted using a temporary stack"], c: "B" },
  { q: "How does Insertion Sort build the final sorted array?", o: ["By picking a pivot and partitioning around it", "By swapping adjacent elements only", "One item at a time, inserting each element into its proper place", "By splitting the array into halves and merging"], c: "C" },
  { q: "What is the best-case time complexity of Insertion Sort when the input is already sorted?", o: ["O(n)", "O(1)", "O(n log n)", "O(n^2)"], c: "A" },
  { q: "In a full binary tree where every non-leaf node has exactly 2 children, how are leaf nodes distributed?", o: ["They reside at the lowest levels of the hierarchy", "They cannot have siblings", "They are placed adjacent to the root", "They are limited to the left subtree"], c: "A" },
  { q: "What do we call a node in a tree that has no children?", o: ["Internal node", "Leaf node", "Root node", "Sibling node"], c: "B" },
  { q: "In a valid Binary Search Tree, where is the node with the maximum value?", o: ["The shallowest leaf", "The leftmost node", "The root node", "The rightmost node"], c: "D" },
  { q: "In Selection Sort, how many total swaps occur in the worst case for an array of size n?", o: ["O(n)", "O(n^2)", "O(1)", "O(n log n)"], c: "A" },
  { q: "Which sorting algorithm is highly efficient for small datasets or nearly-sorted arrays?", o: ["Insertion Sort", "Merge Sort", "Heap Sort", "Selection Sort"], c: "A" },
  { q: "What is the space complexity of an In-order traversal on a balanced tree of n nodes (recursion stack)?", o: ["O(1)", "O(log n)", "O(n^2)", "O(n)"], c: "B" },
  { q: "Performing an In-order traversal on a valid BST produces output in what order?", o: ["Random order", "Sorted ascending order", "Sorted descending order", "The original insertion order"], c: "B" },
  { q: "A BST contains keys [15, 10, 20, 8, 12]. Where is 12 placed relative to 10?", o: ["As a sibling of 20", "As the right child of 10", "As the left child of 10", "As the parent of 15"], c: "B" },
  { q: "Pre-order, post-order, and in-order traversals are all categories of what generic strategy?", o: ["Divide and conquer", "Breadth First Search (BFS)", "Depth First Search (DFS)", "Binary searching"], c: "C" },
  { q: "What is the main space disadvantage of standard Merge Sort vs Bubble/Insertion Sort?", o: ["It modifies the input directly", "It takes O(n^2) auxiliary space", "It requires O(n) extra auxiliary memory for merging", "It runs out of stack from infinite loops"], c: "C" },
  { q: "What is the maximum number of children a node can have in a Binary Tree?", o: ["2", "Unlimited", "1", "3"], c: "A" },
  { q: "Why do we track 'visited' nodes during a DFS traversal on a general graph?", o: ["To prevent infinite loops caused by cycles", "To sort values automatically", "To compute tree height instantly", "To clear memory after visiting"], c: "A" },
  { q: "What is the definition of the height of a tree?", o: ["The number of direct children of the root", "The maximum value stored in the leaves", "The number of edges on the longest path from root to a leaf", "The total count of all nodes"], c: "C" },
  { q: "In an In-order traversal, when is the current node processed (printed)?", o: ["After fully exploring the left subtree", "Before exploring the left subtree", "After fully exploring the right subtree", "Only when recursion returns to the root"], c: "A" },
  { q: "Which sorting algorithm repeatedly finds the minimum from the unsorted part and puts it at the beginning?", o: ["Merge Sort", "Selection Sort", "Bubble Sort", "Insertion Sort"], c: "B" },
  { q: "Which node serves as the top origin point of a tree hierarchy?", o: ["Leaf node", "Ancestor node", "Parent node", "Root node"], c: "D" },
  { q: "What strategy best describes Depth First Search (DFS)?", o: ["Visits nodes in random order", "Visits leaves before the root", "Goes as deep as possible along each branch before backtracking", "Visits nodes level by level"], c: "C" },
  { q: "Which of these is a common application of Depth First Search (DFS)?", o: ["Caching queues for servers", "Shortest path in an unweighted grid", "Level-order printing of a chart", "Detecting cycles in a graph"], c: "D" },
  { q: "Given a binary tree with root 'A', left child 'B', right child 'C', what is the In-order traversal?", o: ["B → C → A", "A → B → C", "B → A → C", "C → B → A"], c: "C" },
  { q: "What is the correct order of steps in an In-order traversal?", o: ["Traverse left, visit root, traverse right", "Visit root, traverse right, traverse left", "Visit root, traverse left, traverse right", "Traverse left, traverse right, visit root"], c: "A" },
  { q: "Which binary tree traversal does NOT use a Depth First (DFS) approach?", o: ["Post-order", "Pre-order", "In-order", "Level-order"], c: "D" },
  { q: "Which data structure is used to implement Depth First Search (DFS) iteratively?", o: ["Linked List", "Stack", "Queue", "Hash Table"], c: "B" },
  { q: "In a BST, what must be true for every node's left subtree?", o: ["All values are less than the node's value", "It has the same height as the right subtree", "All values are greater than the node's value", "It must be empty"], c: "A" },
  { q: "What is the ideal average-case time complexity for searching a key in a balanced BST?", o: ["O(log n)", "O(n^2)", "O(1)", "O(n)"], c: "A" },
];

// DSA flashcards by module (from the professor's notes + standard DSA). [deck, front, back]
export const DSA_MODULE_CARDS = [
  ["Time Complexity", "What is time complexity?", "A measure of how an algorithm's running time grows as the input size n grows, written with Big-O notation (worst case)."],
  ["Time Complexity", "What does Big-O notation describe?", "The upper bound / worst-case growth rate of an algorithm, ignoring constants and lower-order terms (e.g. O(n), O(n^2), O(log n))."],
  ["Time Complexity", "Order these from fastest to slowest growth: O(n²), O(1), O(n log n), O(log n), O(n).", "O(1) < O(log n) < O(n) < O(n log n) < O(n²)."],
  ["Time Complexity", "Why ignore constants in Big-O (e.g. O(2n) → O(n))?", "Big-O describes growth as n → ∞; constant factors don't change the growth rate, so they're dropped."],
  ["Space Complexity", "What is space complexity?", "A measure of the extra (auxiliary) memory an algorithm needs as the input grows, also expressed in Big-O."],
  ["Space Complexity", "What is the space complexity of Merge Sort?", "O(n) — it needs an auxiliary array to merge the halves."],
  ["Space Complexity", "What is auxiliary space vs total space?", "Auxiliary space is the extra memory beyond the input; total space includes the input itself."],
  ["Space Complexity", "Why can recursion add space cost?", "Each recursive call adds a frame to the call stack; depth d uses O(d) stack space (e.g. O(log n) for a balanced tree)."],
  ["Pseudocode", "What is pseudocode and why use it?", "A plain, language-agnostic outline of an algorithm's logic. It lets you think through the approach before writing real code."],
  ["Pseudocode", "Why 'think first' before coding?", "Planning the steps/edge cases in pseudocode avoids bugs and rewrites — you solve the problem on paper, then translate to code."],
  ["Strings", "What is a string in DSA?", "An ordered sequence of characters, typically stored like an array of chars; many problems involve searching, reversing, or comparing substrings."],
  ["Strings", "Why are strings often immutable?", "In many languages (Java, JS, Python) strings can't be changed in place; operations create new strings, which affects time/space cost."],
  ["Arrays", "What is an array?", "A contiguous block of memory storing elements of the same type, accessed by index in O(1) time."],
  ["Arrays", "Why is array access O(1) but insertion O(n)?", "Index access is direct address math; inserting/deleting in the middle requires shifting subsequent elements."],
  ["Sorting", "What is a stable sort?", "A sort that preserves the relative order of elements with equal keys (e.g. Merge Sort is stable; Quick/Selection are not)."],
  ["Sorting", "How does Bubble Sort work?", "Repeatedly steps through the list swapping adjacent out-of-order elements; each pass 'bubbles' the largest remaining value to the end. O(n²)."],
  ["Sorting", "How does Selection Sort work?", "Repeatedly finds the minimum of the unsorted part and places it at the front. O(n²) comparisons, O(n) swaps."],
  ["Sorting", "How does Insertion Sort work?", "Builds the sorted array one element at a time, inserting each into its correct position among the already-sorted prefix. Great for nearly-sorted data."],
  ["Sorting", "How does Merge Sort work?", "Divide and conquer: split the array in half, recursively sort each half, then merge the two sorted halves. O(n log n), stable, O(n) space."],
  ["Linear Search", "How does linear search work and its complexity?", "Check each element one by one until the target is found or the list ends. O(n) time, works on unsorted data."],
  ["Binary Search", "How does binary search work?", "On a SORTED array, repeatedly compare the target to the middle element and discard half each step. O(log n) time."],
  ["Binary Search", "What is the key precondition for binary search?", "The array must be sorted; otherwise the 'discard half' logic is invalid."],
  ["Stack", "What is a stack?", "A LIFO (Last In, First Out) structure. Main ops: push (add to top), pop (remove top), peek (read top) — all O(1)."],
  ["Stack", "Give a use of a stack.", "Function call stack, undo history, expression evaluation, and iterative DFS."],
  ["Queue", "What is a queue?", "A FIFO (First In, First Out) structure. Main ops: enqueue (add to back), dequeue (remove from front) — O(1)."],
  ["Queue", "Give a use of a queue.", "Task scheduling, buffering, and breadth-first search (BFS)."],
  ["Linked List", "What is a linked list?", "A linear structure of nodes where each node holds data and a pointer to the next node. O(1) insert/delete at known positions, O(n) search."],
  ["Linked List", "Linked list vs array — key difference?", "Arrays are contiguous with O(1) indexed access; linked lists are scattered nodes with O(n) access but cheap insertion/deletion."],
  ["Trees", "What is a binary tree?", "A hierarchical structure where each node has at most 2 children (left and right)."],
  ["Trees", "What is a Binary Search Tree (BST)?", "A binary tree where every node's left subtree holds smaller values and right subtree holds larger values, enabling O(log n) search when balanced."],
  ["Trees", "What are the three DFS traversals?", "Pre-order (root, left, right), In-order (left, root, right), and Post-order (left, right, root). In-order on a BST gives sorted output."],
  ["Trees", "What is the height of a tree?", "The number of edges on the longest path from the root to a leaf."],
  ["Trees", "BFS vs DFS on a tree?", "BFS (level-order) visits level by level using a queue; DFS goes deep along a branch before backtracking, using a stack/recursion."],
];

// DSA flashcards distilled from the professor's notes (Medium / GeeksforGeeks). [deck, front, back]
export const DSA_PROF_CARDS = [
  ["Time Complexity", "Big-O in one line?", "A 'speed label' for an algorithm — how its performance changes as input size n grows."],
  ["Time Complexity", "What does O(1) mean?", "Constant time — runtime is the same regardless of input size (e.g. returning a single value)."],
  ["Time Complexity", "Why is O(log n) so fast?", "The problem is halved each step — 10,000 elements need only ~14 steps (e.g. binary search)."],
  ["Time Complexity", "When do you get O(n²)?", "Typically with nested loops where both iterations depend on n."],
  ["Time Complexity", "What is O(n log n)?", "Linearithmic — split work into halves and process each level; slower than O(n), far faster than O(n²) (e.g. merge sort)."],
  ["Space Complexity", "Space complexity in plain English?", "How much extra memory your code uses while running — measured in Big-O, like time."],
  ["Space Complexity", "What does O(1) space mean?", "A fixed amount of extra memory regardless of input size."],
  ["Space Complexity", "What does O(n) space mean?", "Extra memory grows proportionally with input size (e.g. storing n elements)."],
  ["Pseudocode", "Why do beginners get stuck jumping into code?", "Usually a planning gap, not a syntax gap — they have no plan for the next step."],
  ["Pseudocode", "Two rules for good pseudocode?", "One clear step per line; use indentation and action verbs for readability."],
  ["Pseudocode", "Two 'boring but powerful' planning tools?", "Pseudocode and flowcharts — both structure your thinking before real code."],
  ["Strings", "How is a C-style string stored?", "A sequence of characters in consecutive memory cells, ending with a null terminator '\\0'."],
  ["Strings", "Time complexity of common string operations?", "Index access and length are O(1); searching is O(n·m); concatenation is O(n)."],
  ["Strings", "Why prefer std::string over char arrays (C++)?", "It manages memory automatically and has built-in methods — safer than manual char arrays."],
  ["Linear Search", "Space complexity of linear search?", "O(1) — only a couple of extra variables (a counter and the target)."],
  ["Linear Search", "When is linear search the right choice?", "Small or unsorted data where sorting first isn't worth it; works on any collection."],
  ["Binary Search", "Time complexity of binary search?", "O(log n) average/worst, O(1) best — it halves the search space each step."],
  ["Binary Search", "Iterative vs recursive binary search — space cost?", "Iterative uses O(1) space; recursive uses O(log n) for the call stack."],
  ["Binary Search", "A real-world use of binary search?", "Database B-tree indexing, and 'git bisect' to find a faulty commit."],
  ["Linked List", "What two parts make up a linked-list node?", "Data and a link (pointer) to the next node; the first node is the head."],
  ["Linked List", "Three main types of linked list?", "Singly (forward only), doubly (both directions), and circular (last links back to the first)."],
  ["Linked List", "Why are linked lists good at insertion/deletion?", "Nodes aren't contiguous, so you just relink pointers — no shifting elements like an array needs."],
];

// Glossary: term → definition. Terms appearing in card text get linked to these.
export const GLOSSARY = [
  ["Big-O", "Notation for the worst-case growth rate of an algorithm's time or space as input size n grows, ignoring constants."],
  ["Time complexity", "How an algorithm's running time scales with input size n, expressed in Big-O."],
  ["Space complexity", "How much extra (auxiliary) memory an algorithm needs as input size grows."],
  ["Divide and Conquer", "A strategy that splits a problem into smaller subproblems, solves them recursively, and combines the results (e.g. Merge Sort)."],
  ["Stable sort", "A sort that keeps the relative order of equal-keyed elements unchanged."],
  ["Pivot", "An element chosen in Quick Sort to partition the array into smaller and larger parts."],
  ["Array", "A contiguous, index-addressable collection of same-type elements with O(1) access."],
  ["Stack", "A LIFO (Last In, First Out) structure with push/pop/peek operations."],
  ["Queue", "A FIFO (First In, First Out) structure with enqueue/dequeue operations."],
  ["Linked List", "A chain of nodes where each node points to the next; cheap insert/delete, O(n) access."],
  ["Binary Tree", "A tree where each node has at most two children (left and right)."],
  ["Binary Search Tree", "A binary tree where left descendants are smaller and right descendants are larger than each node."],
  ["BST", "Binary Search Tree — left subtree < node < right subtree; in-order traversal yields sorted order."],
  ["Leaf node", "A tree node with no children."],
  ["Root node", "The single top node of a tree, with no parent."],
  ["Height", "The number of edges on the longest path from the root to a leaf."],
  ["DFS", "Depth First Search — explore as deep as possible along a branch before backtracking; uses a stack/recursion."],
  ["BFS", "Breadth First Search — explore level by level; uses a queue."],
  ["In-order", "DFS traversal visiting left subtree, then the node, then the right subtree; yields sorted order on a BST."],
  ["Pre-order", "DFS traversal visiting the node, then left subtree, then right subtree."],
  ["Post-order", "DFS traversal visiting left subtree, then right subtree, then the node."],
  ["Binary Search", "Searching a sorted array by halving the search range each step; O(log n)."],
  ["Linear Search", "Checking each element in turn until the target is found; O(n)."],
  ["Pseudocode", "A plain, language-agnostic sketch of an algorithm's logic before writing real code."],
  ["Bubble Sort", "Repeatedly swaps adjacent out-of-order elements; each pass bubbles the largest to the end. O(n²)."],
  ["Selection Sort", "Repeatedly selects the minimum of the unsorted part and moves it to the front. O(n²)."],
  ["Insertion Sort", "Builds the sorted array one element at a time by inserting each into place. O(n²), great for nearly-sorted data."],
  ["Merge Sort", "Divide-and-conquer: split, recursively sort halves, then merge. O(n log n), stable, O(n) space."],
  ["Quick Sort", "Divide-and-conquer using a pivot to partition; O(n log n) average, O(n²) worst, not stable."],
  ["Node", "A single unit of a linked list or tree, holding data and link(s) to other nodes."],
  ["Head", "The first node of a linked list, the entry point for traversal."],
  ["Null terminator", "The '\\0' character marking the end of a C-style string."],
  ["O(log n)", "Logarithmic time — the problem is halved each step (e.g. binary search)."],
  ["O(n log n)", "Linearithmic time — typical of efficient comparison sorts like Merge Sort."],
];

/* ═══════════════════════════ APTITUDE SUBJECT ═══════════════════════════ */
// Quantitative aptitude (from class notes). Exams: Aptitude-I DILR (MCQ + Theory).
export const APTITUDE_QUIZ = [
  { q: "56% of y is 182. Find y.", o: ["325", "318", "296", "340"], c: "A" },
  { q: "What percent is 42 of 336?", o: ["12.5%", "14%", "8%", "16%"], c: "A" },
  { q: "Rice costs 30% less than wheat. Wheat is how much % more than rice?", o: ["42.85%", "30%", "70%", "33.33%"], c: "A" },
  { q: "A price is increased 10% then decreased 10%. Net change?", o: ["1% loss", "No change", "1% gain", "10% loss"], c: "A" },
  { q: "Sugar price rises 25%. By how much must consumption drop to keep spend the same?", o: ["20%", "25%", "15%", "33.33%"], c: "A" },
  { q: "Passing needs 40%. A student scores 20 marks and fails by 40. Max marks?", o: ["150", "120", "100", "200"], c: "A" },
  { q: "In a 2-way election the loser got 40% and lost by 1000 votes. Total votes?", o: ["5000", "2500", "10000", "4000"], c: "A" },
  { q: "A's salary is 50% more than B's. B's salary is how much % less than A's?", o: ["33.33%", "50%", "66.67%", "25%"], c: "A" },
  { q: "Selling at ₹2880 gives a 20% loss. What is the cost price?", o: ["₹3600", "₹3456", "₹2400", "₹3000"], c: "A" },
  { q: "Two numbers sum to 36 and multiply to 248. Sum of their reciprocals?", o: ["9/62", "1/8", "62/9", "9/31"], c: "A" },
  { q: "A farm has 84 heads and 282 legs (hens & goats). How many hens?", o: ["27", "57", "42", "30"], c: "A" },
  { q: "Ratio of two numbers is 3:8; adding 5 to both makes it 2:5. The smaller number is?", o: ["45", "120", "15", "40"], c: "A" },
  { q: "If A:B = 3:7 and B:C = 9:5, then A:B:C =", o: ["27:63:35", "3:7:5", "27:35:63", "21:63:45"], c: "A" },
  { q: "The fourth proportional of 9, 13, 153 is?", o: ["221", "117", "153", "199"], c: "A" },
  { q: "The mean proportional of 7 and 63 is?", o: ["21", "35", "441", "70"], c: "A" },
  { q: "How many terms are in the expansion of (a+b)^5?", o: ["6", "5", "7", "4"], c: "A" },
  { q: "The 3rd term of (a+b)^5 is?", o: ["10a³b²", "5a⁴b", "10a²b³", "a³b²"], c: "A" },
  { q: "ⁿPᵣ when r = n equals?", o: ["n!", "n", "1", "0"], c: "A" },
  { q: "How many 3-digit numbers can be formed from 2,3,4,5,6 without repetition?", o: ["60", "125", "100", "120"], c: "A" },
  { q: "Arrangements of HISTORY with Y and T always together?", o: ["1440", "720", "5040", "2880"], c: "A" },
  { q: "Solve (n+1)!/(n−1)! = 42 for n.", o: ["6", "7", "5", "21"], c: "A" },
  { q: "Mean of 7, 6, 5, 4, 8, 3, 9?", o: ["6", "5", "7", "42"], c: "A" },
  { q: "Central angle of a pie slice for a value v out of total T?", o: ["(v/T)×360°", "(v/T)×100", "(v/T)×180°", "v/360"], c: "A" },
  { q: "Team of 6 from 9 men & 6 women with at least 3 women — number of selections?", o: ["2275", "1680", "924", "540"], c: "A" },
];

export const APTITUDE_MODULE_CARDS = [
  ["Percentage", "How do you find x% of y?", "(x/100) × y."],
  ["Percentage", "If A is p% more than B, how much % less is B than A?", "p/(100+p) × 100. e.g. +50% ⇒ B is 33.33% less."],
  ["Percentage", "Net effect of increasing then decreasing by the same x%?", "A net loss of (x²/100)% — e.g. ±10% ⇒ 1% loss."],
  ["Percentage", "If a price rises r%, how much to cut consumption to keep spend fixed?", "r/(100+r) × 100. e.g. +25% ⇒ cut 20%."],
  ["Percentage", "Cost price from a loss% sale: SP = ₹2880 at 20% loss ⇒ CP?", "CP = SP × 100/(100−loss%) = 2880 × 100/80 = ₹3600."],
  ["Ratio & Proportion", "Fourth proportional of a, b, c?", "x where a:b = c:x, so x = b·c/a."],
  ["Ratio & Proportion", "Mean proportional of a and b?", "√(a·b)."],
  ["Ratio & Proportion", "How to combine A:B and B:C into A:B:C?", "Scale both so B matches, then read across — e.g. 3:7 & 9:5 ⇒ 27:63:35."],
  ["Ratio & Proportion", "Theorem of equal ratios: if a/p = b/q = c/r = k, then k = ?", "(a+b+c)/(p+q+r)."],
  ["Linear Equations", "Sum of reciprocals of x and y?", "(x+y)/(xy)."],
  ["Linear Equations", "Heads-and-legs (hens & goats) — how to set it up?", "x + y = heads; 2x + 4y = legs; solve the two equations."],
  ["Linear Equations", "Sum of n consecutive integers centred at x?", "n·x (the terms are symmetric about the middle one)."],
  ["Statistics", "Mean of a grouped frequency distribution?", "x̄ = Σ(fᵢxᵢ) / Σfᵢ, using class midpoints for xᵢ."],
  ["Statistics", "Median of grouped data?", "L + [ (n/2 − cf) / f_m ] × c, where L = lower limit of the median class."],
  ["Statistics", "Mode of grouped data?", "L + [ (f_m − f₁) / (2f_m − f₁ − f₂) ] × c."],
  ["Statistics", "Central angle of a pie slice?", "(value / total) × 360°."],
  ["Statistics", "Median of raw data with even n?", "Average of the (n/2)th and (n/2 + 1)th ordered values."],
  ["Binomial", "How many terms in the expansion of (a+b)ⁿ?", "n + 1 (one more than the power)."],
  ["Binomial", "General term T(r+1) of (a+b)ⁿ?", "ⁿCᵣ · a^(n−r) · b^r — note r is one less than the term number."],
  ["Binomial", "Middle term(s) of (a+b)ⁿ?", "If n is even: the (n/2 + 1)th term. If n is odd: the ((n+1)/2)th and ((n+3)/2)th terms."],
  ["Permutations & Combinations", "Permutations ⁿPᵣ — formula and when?", "n!/(n−r)! — use when order matters."],
  ["Permutations & Combinations", "Combinations ⁿCᵣ — formula and when?", "n!/(r!(n−r)!) — use when order doesn't matter."],
  ["Permutations & Combinations", "Useful symmetry of combinations?", "ⁿCᵣ = ⁿC₍ₙ₋ᵣ₎."],
  ["Permutations & Combinations", "Arrangements of a word with a repeated letter?", "n! / (count of each repeat)! — e.g. TAMIM = 5!/2! = 60."],
  ["Permutations & Combinations", "Count arrangements with two specific letters always together?", "Treat them as one block: (n−1)! × 2!."],
  ["Permutations & Combinations", "Arrange so that no two vowels are together?", "Place the consonants first, then slot vowels into the gaps between them."],
];

// Solve-it problems: { topic, q(LaTeX), answer, accept[], solution(LaTeX steps), revealOnly? }
export const APTITUDE_PROBLEMS = [
  { topic: "Percentage", q: "56\\% \\text{ of } y = 182. \\quad \\text{Find } y.", answer: "325",
    solution: "“% of” means multiply, and $56\\%=\\frac{56}{100}$. So:\n$$\\frac{56}{100}\\times y = 182$$\nTo isolate $y$, multiply both sides by $\\frac{100}{56}$:\n$$y = 182\\times\\frac{100}{56} = \\frac{18200}{56}$$\nDivide: $18200\\div 56 = 325$.\n$$\\boxed{y = 325}$$\nCheck: $56\\%$ of $325 = 0.56\\times325 = 182$. ✓" },
  { topic: "Percentage", q: "\\text{What percent is } 42 \\text{ of } 336?", answer: "12.5", accept: ["12.5%"],
    solution: "“What percent is A of B” $=\\dfrac{A}{B}\\times100$. Here $A=42,\\ B=336$:\n$$\\frac{42}{336}\\times100$$\nSimplify $\\frac{42}{336}$: both divide by 42, giving $\\frac{1}{8}$.\n$$\\frac{1}{8}\\times100 = 12.5$$\n$$\\boxed{12.5\\%}$$" },
  { topic: "Percentage", q: "\\text{A price rises } 10\\% \\text{ then falls } 10\\%. \\text{ Net change } \\%?", answer: "1", accept: ["1%", "-1", "1% loss"],
    solution: "Take a convenient start of ₹100.\nStep 1 — rise $10\\%$: $100 + 10\\%\\text{ of }100 = 100+10 = 110$.\nStep 2 — fall $10\\%$ (of the NEW value 110): $10\\%\\text{ of }110 = 11$, so $110-11 = 99$.\nNet: ended at $99$ vs start $100$ → a drop of $1$.\n$$\\boxed{1\\%\\text{ loss}}$$\nWhy it isn't 0: the fall is taken on the larger amount. In general $+x\\%$ then $-x\\%$ gives a net $-\\dfrac{x^2}{100}\\%$ (here $\\frac{10^2}{100}=1\\%$)." },
  { topic: "Percentage", q: "\\text{Sugar price rises } 25\\%. \\text{ \\% cut in consumption to keep spend fixed?}", answer: "20", accept: ["20%"],
    solution: "Spend $=$ price $\\times$ quantity. Keep spend fixed while price rises $25\\%$.\nLet old price $=100$, old qty $=1$ (spend $=100$). New price $=125$.\nNew qty $=\\dfrac{\\text{spend}}{\\text{new price}}=\\dfrac{100}{125}=0.8$.\nDrop $=1-0.8 = 0.2 = 20\\%$.\n$$\\boxed{20\\%}$$\nShortcut: cut $=\\dfrac{r}{100+r}\\times100 = \\dfrac{25}{125}\\times100 = 20\\%$." },
  { topic: "Percentage", q: "\\text{Pass mark } 40\\%. \\text{ Scores } 20, \\text{ fails by } 40. \\text{ Max marks?}", answer: "150",
    solution: "“Fails by 40” means he needed 40 more to reach the pass mark.\nPassing marks $= \\text{scored} + \\text{shortfall} = 20+40 = 60$.\nPassing is $40\\%$ of the maximum $x$:\n$$\\frac{40}{100}\\times x = 60$$\n$$x = 60\\times\\frac{100}{40} = \\boxed{150}$$" },
  { topic: "Percentage", q: "\\text{Selling at ₹2880 gives a } 20\\% \\text{ loss. Cost price?}", answer: "3600", accept: ["₹3600"],
    solution: "A $20\\%$ loss means SP is $100-20 = 80\\%$ of CP.\n$$SP = \\frac{80}{100}\\times CP \\Rightarrow 2880 = 0.8\\,CP$$\n$$CP = \\frac{2880}{0.8} = 2880\\times\\frac{100}{80} = \\boxed{₹3600}$$\nCheck: $20\\%$ of 3600 $=720$, and $3600-720 = 2880$. ✓" },
  { topic: "Ratio & Proportion", q: "\\text{Ratio } 3:8;\\ \\text{adding 5 to both} \\to 2:5.\\ \\text{Smaller number?}", answer: "45",
    solution: "Let the numbers be $3x$ and $8x$ (so their ratio is exactly $3:8$).\nAfter adding 5 to each:\n$$\\frac{3x+5}{8x+5} = \\frac{2}{5}$$\nCross-multiply:\n$$5(3x+5) = 2(8x+5)$$\n$$15x+25 = 16x+10$$\n$$25-10 = 16x-15x \\Rightarrow x = 15$$\nSmaller number $= 3x = 3\\times15 = \\boxed{45}$." },
  { topic: "Ratio & Proportion", q: "\\text{Fourth proportional of } 9,\\ 13,\\ 153?", answer: "221",
    solution: "The fourth proportional $x$ satisfies $a:b = c:x$, i.e. $\\dfrac{a}{b}=\\dfrac{c}{x}$.\n$$\\frac{9}{13} = \\frac{153}{x}$$\nCross-multiply: $9x = 13\\times153$.\n$$x = \\frac{13\\times153}{9} = \\frac{1989}{9} = \\boxed{221}$$" },
  { topic: "Ratio & Proportion", q: "\\text{Mean proportional of } 7 \\text{ and } 63?", answer: "21",
    solution: "The mean proportional $x$ of $a,b$ satisfies $a:x = x:b$, so $x^2 = ab$.\n$$x^2 = 7\\times63 = 441$$\n$$x = \\sqrt{441} = \\boxed{21}$$" },
  { topic: "Linear Equations", q: "\\text{Two numbers sum to } 36,\\ \\text{product } 248.\\ \\text{Sum of reciprocals?}", answer: "9/62", accept: ["0.145"],
    solution: "Let the numbers be $x,y$ with $x+y = 36$ and $xy = 248$.\nThe sum of reciprocals has a neat identity:\n$$\\frac{1}{x}+\\frac{1}{y} = \\frac{y+x}{xy} = \\frac{x+y}{xy}$$\nSubstitute the known sum and product:\n$$= \\frac{36}{248}$$\nSimplify (divide top and bottom by 4):\n$$\\boxed{\\frac{9}{62}}$$" },
  { topic: "Linear Equations", q: "\\text{84 heads, 282 legs (hens \\& goats). Number of hens?}", answer: "27",
    solution: "Each animal has 1 head; a hen has 2 legs, a goat has 4. Let hens $=x$, goats $=y$.\n$$x+y = 84 \\quad(\\text{heads})$$\n$$2x+4y = 282 \\quad(\\text{legs})$$\nMultiply the first by 2: $2x+2y = 168$. Subtract from the legs equation:\n$$(2x+4y)-(2x+2y) = 282-168 \\Rightarrow 2y = 114 \\Rightarrow y = 57$$\nSo goats $=57$, and hens $= 84-57 = \\boxed{27}$." },
  { topic: "Linear Equations", q: "\\text{Sum of 5 consecutive integers is } 335.\\ \\text{Smallest + largest?}", answer: "134",
    solution: "Center the 5 numbers on $x$: $\\;x-2,\\ x-1,\\ x,\\ x+1,\\ x+2$.\nTheir sum collapses to $5x$ (the $\\pm$ terms cancel):\n$$5x = 335 \\Rightarrow x = 67$$\nNumbers: $65,66,67,68,69$. Smallest + largest $= 65+69 = \\boxed{134}$.\n(Equivalently it's $2x = 134$ — the extremes average to the middle.)" },
  { topic: "Binomial", q: "\\text{Number of terms in } (a+b)^5?", answer: "6",
    solution: "Expanding $(a+b)^n$ gives powers of $a$ from $a^n$ down to $a^0$ — that's $0,1,\\dots,n$, i.e. $n+1$ values.\nHere $n=5$:\n$$\\text{terms} = n+1 = 5+1 = \\boxed{6}$$" },
  { topic: "Binomial", q: "\\text{Find the 3rd term of } (a+b)^5.", answer: "10a^3b^2", accept: ["10a3b2", "10a³b²"],
    solution: "General term: $T_{r+1} = {}^nC_r\\,a^{\\,n-r}b^{\\,r}$. The “3rd term” means $r+1=3$, so $r=2$ (and $n=5$).\n$$T_3 = {}^5C_2\\,a^{5-2}b^{2} = {}^5C_2\\,a^{3}b^{2}$$\nCompute ${}^5C_2 = \\dfrac{5\\times4}{2\\times1} = 10$.\n$$\\boxed{T_3 = 10a^{3}b^{2}}$$" },
  { topic: "Binomial", q: "\\text{Middle term of } \\left(3x+\\tfrac{1}{\\sqrt{x}}\\right)^6 ?", revealOnly: true, answer: "540x^{3/2}",
    solution: "Number of terms $= n+1 = 7$ (odd), so there's one middle term: the $\\frac{7+1}{2}=4$th term, i.e. $r=3$.\n$$T_4 = {}^6C_3\\,(3x)^{3}\\left(x^{-1/2}\\right)^{3}$$\n${}^6C_3 = 20$, $(3x)^3 = 27x^3$, $\\left(x^{-1/2}\\right)^3 = x^{-3/2}$.\n$$T_4 = 20\\cdot27\\cdot x^{3-3/2} = 540\\,x^{3/2}$$\n$$\\boxed{540x^{3/2}} \\;=\\; 540x\\sqrt{x}$$" },
  { topic: "Permutations & Combinations", q: "\\text{How many 3-digit numbers from } 2,3,4,5,6 \\text{ without repetition?}", answer: "60",
    solution: "Fill 3 positions left to right; no digit repeats (order matters → permutation).\nHundreds: 5 choices. Tens: 4 left. Units: 3 left.\n$$5\\times4\\times3 = \\boxed{60}$$\n(This is exactly ${}^5P_3 = \\dfrac{5!}{2!} = 60$.)" },
  { topic: "Permutations & Combinations", q: "\\text{Arrangements of HISTORY with Y and T always together?}", answer: "1440",
    solution: "HISTORY has 7 distinct letters. “Y and T together” → glue them into one block, so you arrange $6$ items (the block + H,I,S,O,R).\n$$6! = 720 \\text{ ways}$$\nInside the block, Y and T can swap: $2! = 2$ ways.\n$$6!\\times2! = 720\\times2 = \\boxed{1440}$$" },
  { topic: "Permutations & Combinations", q: "\\text{Solve } \\dfrac{(n+1)!}{(n-1)!}=42.", answer: "6",
    solution: "Expand the factorial ratio — $(n+1)! = (n+1)(n)(n-1)!$, so the $(n-1)!$ cancels:\n$$\\frac{(n+1)(n)(n-1)!}{(n-1)!} = (n+1)(n) = 42$$\n$$n^2+n-42 = 0$$\nFactor: $(n-6)(n+7) = 0 \\Rightarrow n = 6$ or $n=-7$. Reject the negative.\n$$\\boxed{n = 6}$$" },
  { topic: "Permutations & Combinations", q: "\\text{Team of 6 from 9 men \\& 6 women, at least 3 women. Selections?}", answer: "2275",
    solution: "“At least 3 women” means 3, 4, 5, or 6 women (the rest are men, to total 6). Add the cases:\n$$\\binom{6}{3}\\binom{9}{3} + \\binom{6}{4}\\binom{9}{2} + \\binom{6}{5}\\binom{9}{1} + \\binom{6}{6}\\binom{9}{0}$$\n$$= (20)(84) + (15)(36) + (6)(9) + (1)(1)$$\n$$= 1680 + 540 + 54 + 1 = \\boxed{2275}$$" },
  { topic: "Statistics", q: "\\text{Mean of } 7,6,5,4,8,3,9?", answer: "6",
    solution: "Mean $= \\dfrac{\\text{sum of values}}{\\text{count}}$.\nSum $= 7+6+5+4+8+3+9 = 42$; count $= 7$.\n$$\\bar{x} = \\frac{42}{7} = \\boxed{6}$$" },
  { topic: "Statistics", q: "\\text{A pie slice for ₹2000 spans } 60°.\\ \\text{Total investment?}", answer: "12000", accept: ["₹12000"],
    solution: "In a pie chart a slice's angle is proportional to its value: $\\dfrac{\\text{value}}{\\text{total}} = \\dfrac{\\text{angle}}{360°}$.\n$$\\frac{2000}{T} = \\frac{60}{360} = \\frac{1}{6}$$\n$$T = 2000\\times6 = \\boxed{₹12000}$$" },
  { topic: "Statistics", q: "\\text{Central angle for marks } 90 \\text{ out of total } 400?", answer: "81", accept: ["81°"],
    solution: "Central angle $= \\dfrac{\\text{value}}{\\text{total}}\\times360°$.\n$$= \\frac{90}{400}\\times360° = 0.225\\times360°$$\n$$= \\boxed{81°}$$" },
];

export const APTITUDE_FORMULAS = [
  { topic: "Percentage", items: ["x\\% \\text{ of } y = \\frac{x}{100}\\,y", "\\text{A is }p\\%\\text{ more than B} \\Rightarrow \\text{B is }\\frac{p}{100+p}\\times100\\%\\text{ less}", "+x\\%\\text{ then }-x\\% \\Rightarrow \\text{net }-\\frac{x^2}{100}\\%", "\\text{price}\\uparrow r\\% \\Rightarrow \\text{cut use by }\\frac{r}{100+r}\\times100\\%"] },
  { topic: "Ratio & Proportion", items: ["\\text{Fourth proportional: } a:b=c:x \\Rightarrow x=\\frac{bc}{a}", "\\text{Mean proportional of }a,b = \\sqrt{ab}", "\\frac{a}{p}=\\frac{b}{q}=\\frac{c}{r}=\\frac{a+b+c}{p+q+r}"] },
  { topic: "Linear Equations", items: ["\\frac{1}{x}+\\frac{1}{y}=\\frac{x+y}{xy}", "\\text{Heads \\& legs: } x+y=H,\\ 2x+4y=L"] },
  { topic: "Statistics", items: ["\\bar{x}=\\frac{\\sum f_i x_i}{\\sum f_i}", "\\text{Median}=L+\\frac{\\frac{n}{2}-cf}{f_m}\\times c", "\\text{Mode}=L+\\frac{f_m-f_1}{2f_m-f_1-f_2}\\times c", "\\text{Pie angle}=\\frac{\\text{value}}{\\text{total}}\\times360°"] },
  { topic: "Binomial", items: ["(a+b)^n \\text{ has } n+1 \\text{ terms}", "T_{r+1}={}^nC_r\\,a^{n-r}b^{r}", "{}^nC_r=\\frac{n!}{r!(n-r)!}"] },
  { topic: "Permutations & Combinations", items: ["{}^nP_r=\\frac{n!}{(n-r)!}\\ (\\text{order matters})", "{}^nC_r=\\frac{n!}{r!(n-r)!}\\ (\\text{order doesn't})", "{}^nC_r={}^nC_{n-r}", "\\text{Repeats: }\\frac{n!}{p!\\,q!\\cdots}", "\\text{Together} \\Rightarrow (n-1)!\\times2!"] },
];

